# Based on https://debezium.io/documentation/reference/1.5/tutorial.html
---
version: "2"
services:

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - howto-debeizum-to-snowflake_kafka-network

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - "9092:9092"
    environment: 
      #ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on: 
      - zookeeper
    links:
      - zookeeper:zookeeper
    networks:
      - howto-debeizum-to-snowflake_kafka-network

  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    networks: 
      - howto-debeizum-to-snowflake_db-network

  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports: 
      - "8083:8083"
    environment: 
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on: 
      - zookeeper
      - kafka
      - mysql
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - mysql:mysql
    networks:
      - howto-debeizum-to-snowflake_kafka-network
      - howto-debeizum-to-snowflake_db-network

networks: 
  howto-debeizum-to-snowflake_kafka-network: 
  howto-debeizum-to-snowflake_db-network: