# Based on https://debezium.io/documentation/reference/1.5/tutorial.html
# Run as:
#   docker-compose -f docker-compose-debezium.yml
---
version: "2"
services:

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - howto-debeizum-to-snowflake_kafka-network

  # After start CDC, you can consume the events using this command
  # MySQL: 
  #   docker-compose -f docker-compose-debezium.yml exec kafka /kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --from-beginning --property print.key=true --topic dbserver1.inventory.pet
  # Postgres:
  #   docker-compose -f docker-compose-debezium.yml exec kafka /kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --from-beginning --property print.key=true --topic dbserver1.inventory.accounts
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - "9092:9092"
    environment: 
      #ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on: 
      - zookeeper
    links:
      - zookeeper:zookeeper
    networks:
      - howto-debeizum-to-snowflake_kafka-network

  # docker-compose -f docker-compose-debezium.yml exec mysql bash -c 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD inventory'
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    networks: 
      - howto-debeizum-to-snowflake_db-network
  
  # docker-compose -f docker-compose-debezium.yml exec postgres env PGOPTIONS="--search_path=inventory" bash -c 'psql -U $POSTGRES_USER postgres'
  postgres:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
    networks: 
      - howto-debeizum-to-snowflake_db-network
  
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports: 
      - "8083:8083"
    environment: 
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on: 
      - zookeeper
      - kafka
      - mysql
      - postgres
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - mysql:mysql
      - postgres:postgres
    networks:
      - howto-debeizum-to-snowflake_kafka-network
      - howto-debeizum-to-snowflake_db-network

networks: 
  howto-debeizum-to-snowflake_kafka-network: 
  howto-debeizum-to-snowflake_db-network: